version: '3.3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./data/html:/var/www/html
      - ./logs/nginx:/var/log/nginx
    ports:
      - "8080:80"
    links:
      - wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - ./data/html:/var/www/html
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST:  db:3306
      WORDPRESS_DB_USER: testuser
      WORDPRESS_DB_PASSWORD: testpassword
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:5.7
    volumes:
      - ./data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: wordpress
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpassword

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    links:
      - db:mysql
    ports:
      - "8081:80"
    environment:
      MYSQL_ROOT_PASSWORD: testpassword

  prometheus: 
    image: prom/prometheus:latest
    volumes:
      - './:/etc/prometheus/'
      - ./prometheus/alert.rules:/etc/prometheus/alert.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
 
  node-exporter:
    image: prom/node-exporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - --path.procfs=/host/proc
      - --path.sysfs=/host/sys
      - --collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)
    ports:
      - 9100:9100  

  mysqld-exporter:
    image: prom/mysqld-exporter:latest
    volumes:
      - ./sql_exporter.cnf:/.my.cnf
    command:
      - --config.my-cnf=.my.cnf
    ports:
      - "9104:9104"

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    volumes:
      - ./blackbox.yml:/config/blackbox.yml
    command:
      - '--config.file=/config/blackbox.yml'
    ports:
      - "9115:9115"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    command:
      - --nginx.scrape-uri=http://172.23.32.1:80/nginx_status
    ports:                                                                                                            
      - "9113:9113"

  victoriametrics:
    container_name: victoriametrics
    image: victoriametrics/victoria-metrics:latest
    ports:
      - 8428:8428
      - 8089:8089
      - 8089:8089/udp
      - 2003:2003
      - 2003:2003/udp
      - 4242:4242
    volumes:
       - ./vmdata:/vmdata
    command:
      - '--storageDataPath=/vmdata'
      - '--retentionPeriod=14'
      - '--loggerFormat=json'
      - '--httpListenAddr=:8428'

  grafana:
    image: grafana/grafana:latest
    user: root
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    container_name: grafana
    hostname: grafana
    environment:
      TZ: "Europe/Moscow"

  alertmanager:
    image: prom/alertmanager:latest
    user: root
    ports:
      - 9093:9093
    volumes:
      - ./:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/config.yml'
      - '--storage.path=/alertmanager'

  alertmanager-bot:
    command:
      - --alertmanager.url=http://172.23.32.1:9093
      - --log.level=info
      - --store=bolt
      - --bolt.path=/data/bot.db
      - --telegram.admin=192195634
      - --telegram.token=7175330551:AAE9PBfXkkw1G-Axm8xfd606eqeLs5aU08c
    image: metalmatze/alertmanager-bot:latest
    user: root
    ports:
      - 8082:8082
    environment:
      TZ: "Europe/Moscow"
    volumes:
      - ./data:/data

  mailhog:
    image: mailhog/mailhog:latest
    ports:
      - '8025:8025'
      - '1025:1025'

